"""Database layer — SQLAlchemy models + connection management."""
from ontology_store.db.card_models import Card, CardRef, KNOWN_CARD_KINDS
from ontology_store.db.relation_models import RelationType
from ontology_store.db.stats_models import CARDINALITY_TIERS, ColumnStat, TableStat
from ontology_store.db.engine import Base, Database, get_session
from ontology_store.db.eval_models import (
    EvalCase,
    EvalMetric,
    EvalResult,
    EvalRun,
)
from ontology_store.db.inference_models import (
    CausalCandidate,
    DataProtectionHint,
)
from ontology_store.db.models import (
    AssetAnnotationProvenance,
    Catalog,
    ClusterMetadata,
    ColumnDescription,
    ColumnExt,
    ColumnMetadata,
    ColumnProgrammaticDescription,
    DatabaseMetadata,
    HierarchyAudit,
    LineageEdge,
    OperatingRegion,
    Organization,
    SchemaCatalog,
    SchemaExt,
    SchemaMetadata,
    Source,
    TableDescription,
    TableExt,
    TableMetadata,
    TableProgrammaticDescription,
)

__all__ = [
    "Base",
    "Database",
    "get_session",
    "Organization",
    "OperatingRegion",
    "Source",
    "Catalog",
    "SchemaCatalog",
    "DatabaseMetadata",
    "ClusterMetadata",
    "SchemaMetadata",
    "SchemaExt",
    "TableMetadata",
    "TableExt",
    "TableDescription",
    "TableProgrammaticDescription",
    "ColumnMetadata",
    "ColumnExt",
    "ColumnDescription",
    "ColumnProgrammaticDescription",
    "AssetAnnotationProvenance",
    "LineageEdge",
    "HierarchyAudit",
    "EvalCase",
    "EvalRun",
    "EvalResult",
    "EvalMetric",
    "CausalCandidate",
    "DataProtectionHint",
    "Card",
    "CardRef",
    "KNOWN_CARD_KINDS",
    "TableStat",
    "ColumnStat",
    "CARDINALITY_TIERS",
    "RelationType",
]
